// Base de données locale de mots secrets pour le jeu Undercover.
export const INITIAL_THEMES = {
    nourriture: {
        name: "🍔 Nourriture & Boissons",
        icon: "fa-hamburger",
        color: "from-amber-500 to-orange-600",
        pairs: [
            { civil: "Coca-Cola", undercover: "Pepsi" },
            { civil: "Burger", undercover: "Kebab" },
            { civil: "Chocolat noir", undercover: "Chocolat au lait" },
            { civil: "Pizza", undercover: "Quiche" },
            { civil: "Café", undercover: "Thé" },
            { civil: "Raclette", undercover: "Fondue" },
            { civil: "Frites", undercover: "Potatoes" },
            { civil: "Croissant", undercover: "Pain au chocolat" },
            { civil: "Bière", undercover: "Cidre" },
            { civil: "Crêpe", undercover: "Gaufre" },
            { civil: "Pâtes", undercover: "Riz" },
            { civil: "Beurre", undercover: "Margarine" },
            { civil: "Sel", undercover: "Poivre" },
            { civil: "Ketchup", undercover: "Mayonnaise" },
            { civil: "Sushi", undercover: "Maki" },
            { civil: "Fraise", undercover: "Framboise" },
            { civil: "Eau plate", undercover: "Eau gazeuse" },
            { civil: "Miel", undercover: "Sirop d'érable" },
            { civil: "Glace", undercover: "Sorbet" },
            { civil: "Lait", undercover: "Crème fraîche" },
            { civil: "Nutella", undercover: "Pâte à tartiner" },
            { civil: "Whisky", undercover: "Rhum" },
            { civil: "Baguette", undercover: "Pain de mie" },
            { civil: "Saucisson", undercover: "Chorizo" },
            { civil: "Champagne", undercover: "Prosecco" }
        ]
    },
    pop_culture: {
        name: "🎬 Pop Culture & Geek",
        icon: "fa-film",
        color: "from-purple-500 to-indigo-600",
        pairs: [
            { civil: "Harry Potter", undercover: "Percy Jackson" },
            { civil: "Batman", undercover: "Iron Man" },
            { civil: "Star Wars", undercover: "Star Trek" },
            { civil: "Netflix", undercover: "Prime Video" },
            { civil: "TikTok", undercover: "Instagram" },
            { civil: "PlayStation", undercover: "Xbox" },
            { civil: "Pikachu", undercover: "Évoli" },
            { civil: "Marvel", undercover: "DC Comics" },
            { civil: "Mario", undercover: "Sonic" },
            { civil: "Zelda", undercover: "Link" },
            { civil: "iPhone", undercover: "Android" },
            { civil: "ChatGPT", undercover: "Google Gemini" },
            { civil: "Spotify", undercover: "Deezer" },
            { civil: "Fortnite", undercover: "Call of Duty" },
            { civil: "Naruto", undercover: "Sasuke" },
            { civil: "YouTube", undercover: "Twitch" },
            { civil: "Simpsons", undercover: "South Park" },
            { civil: "Minecraft", undercover: "Roblox" },
            { civil: "Shrek", undercover: "Monstres Cie" },
            { civil: "Spider-Man", undercover: "Spider-Gwen" },
            { civil: "One Piece", undercover: "Dragon Ball" },
            { civil: "Disney", undercover: "Pixar" },
            { civil: "Pac-Man", undercover: "Tetris" },
            { civil: "Game of Thrones", undercover: "Le Seigneur des Anneaux" },
            { civil: "Elon Musk", undercover: "Mark Zuckerberg" }
        ]
    },
    hardcore: {
        name: "🧠 Mode Hardcore (Abstrait)",
        icon: "fa-brain",
        color: "from-rose-500 to-red-600",
        pairs: [
            { civil: "Temps", undercover: "Durée" },
            { civil: "Vide", undercover: "Néant" },
            { civil: "Confiance", undercover: "Naïveté" },
            { civil: "Mémoire", undercover: "Souvenir" },
            { civil: "Objectif", undercover: "Ambition" },
            { civil: "Rêve", undercover: "Illusion" },
            { civil: "Liberté", undercover: "Indépendance" },
            { civil: "Justice", undercover: "Égalité" },
            { civil: "Peur", undercover: "Angoisse" },
            { civil: "Tristesse", undercover: "Mélancolie" },
            { civil: "Sagesse", undercover: "Intelligence" },
            { civil: "Secret", undercover: "Mystère" },
            { civil: "Hasard", undercover: "Destin" },
            { civil: "Vérité", undercover: "Réalité" },
            { civil: "Espace", undercover: "Univers" },
            { civil: "Origine", undercover: "Source" },
            { civil: "Esprit", undercover: "Pensée" },
            { civil: "Silence", undercover: "Calme" },
            { civil: "Destructeur", undercover: "Ravager" },
            { civil: "Sympathie", undercover: "Empathie" },
            { civil: "Art", undercover: "Design" },
            { civil: "Erreur", undercover: "Faute" },
            { civil: "Croyance", undercover: "Opinion" },
            { civil: "Haine", undercover: "Colère" }
        ]
    },
    vie_quotidienne: {
        name: "🏡 Vie Quotidienne",
        icon: "fa-home",
        color: "from-emerald-500 to-teal-600",
        pairs: [
            { civil: "Lit", undercover: "Canapé" },
            { civil: "Ordinateur", undercover: "Téléphone" },
            { civil: "Voiture", undercover: "Moto" },
            { civil: "Stylo", undercover: "Crayon" },
            { civil: "Douche", undercover: "Bain" },
            { civil: "Montre", undercover: "Horloge" },
            { civil: "Porte", undercover: "Fenêtre" },
            { civil: "Miroir", undercover: "Tableau" },
            { civil: "Clé", undercover: "Badge" },
            { civil: "Livre", undercover: "Magazine" },
            { civil: "Ciseaux", undercover: "Couteau" },
            { civil: "Sac à dos", undercover: "Valise" },
            { civil: "Chaussette", undercover: "Chaussure" },
            { civil: "Parapluie", undercover: "Manteau" },
            { civil: "Lunettes", undercover: "Lentilles" },
            { civil: "Oreiller", undercover: "Couette" },
            { civil: "Brosse à dents", undercover: "Dentifrice" },
            { civil: "Savon", undercover: "Gel douche" },
            { civil: "Verre", undercover: "Tasse" },
            { civil: "Balai", undercover: "Aspirateur" },
            { civil: "Casserole", undercover: "Poêle" },
            { civil: "Frigo", undercover: "Congélateur" },
            { civil: "Vis", undercover: "Clou" },
            { civil: "Radiateur", undercover: "Cheminée" },
            { civil: "Serviette", undercover: "Gant de toilette" }
        ]
    },
    fun_soiree: {
        name: "🎉 Soirée & Fun",
        icon: "fa-glass-cheers",
        color: "from-pink-500 to-rose-600",
        pairs: [
            { civil: "Gueule de bois", undercover: "Fin de soirée" },
            { civil: "Vérité ou Action", undercover: "Je n'ai jamais" },
            { civil: "Vodka Pomme", undercover: "Gin Tonic" },
            { civil: "Grasse matinée", undercover: "Sieste d'après-midi" },
            { civil: "Pizzas froides", undercover: "Kebabs de nuit" },
            { civil: "Karaoké", undercover: "Blind test" },
            { civil: "Boîte de nuit", undercover: "Bar dansant" },
            { civil: "Dragueur", undercover: "Romantique" },
            { civil: "Tire-bouchon", undercover: "Décapsuleur" },
            { civil: "Secret de polichinelle", undercover: "Ragot de couloir" },
            { civil: "DJ", undercover: "Playlist Spotify" },
            { civil: "Flirt", undercover: "Coup de foudre" },
            { civil: "Late-night discussion", undercover: "Confession intime" }
        ]
    },
    autre: {
        name: "🌀 Autre & Divers",
        icon: "fa-folder-open",
        color: "from-slate-500 to-zinc-600",
        pairs: [
            { civil: "Soleil", undercover: "Lune" },
            { civil: "Chien", undercover: "Chat" },
            { civil: "Or", undercover: "Argent" },
            { civil: "Mer", undercover: "Océan" },
            { civil: "Guitare", undercover: "Piano" }
        ]
    }
};
